replicas: 3

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.kube.local
persistence:
  enabled: true
  storageClassName: nfs

initChownData:
  ## If false, data ownership will not be reset at startup
  ## This allows the grafana-server to be run with an arbitrary user
  ##
  enabled: false


# Administrator credentials when not using an existing secret (see below)
adminUser: admin
adminPassword: admin

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: nyuffi-prometheus
     type: prometheus
     url: http://nyuffiprometheus-server
     access: proxy
     isDefault: true


dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'grafana-dashboards-kubernetes'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
    - name: 'grafana-dashboards-immich'
      orgId: 1
      folder: 'immich'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/grafana-dashboards-immich
    - name: 'grafana-dashboards-node'
      orgId: 1
      folder: 'node'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/grafana-dashboards-node   

dashboards:
  grafana-dashboards-kubernetes:
    k8s-system-api-server:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
      token: ''
    k8s-system-coredns:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
      token: ''
    k8s-views-global:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
      token: ''
    k8s-views-namespaces:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
      token: ''
    k8s-views-nodes:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
      token: ''
    k8s-views-pods:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
      token: ''
  grafana-dashboards-immich:
    immich-dashboard:
      url: https://raw.githubusercontent.com/friendlyFriend4000/prometheus-immich-exporter/master/grafana/dashboard-immich.json
      token: ''
  grafana-dashboards-node:
    node-dashboard:
      gnetId: 1860
      revision: 36
      datasource: nyuffi-prometheus

networkPolicy:
  enabled: true
